version: "3.9"

services:
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    restart: always
    environment: 
      POSTGRES_USER: geoservice
      POSTGRES_PASSWORD: geoservice
    volumes:
      - data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "5000:5000"
    restart: always
    depends_on: [postgres]
    environment:
      GEOSERVICE_DB_HOST: postgres
      GEOSERVICE_SERVER_ADDR: 0.0.0.0

volumes:
  data: {}
