version: "3.9"

# TODO: maybe importcsv as a service
services:
  postgres:
    image: "postgres:14"
    ports:
      - "5433:5432"
    restart: always
    environment: 
      POSTGRES_USER: findhotel
      POSTGRES_PASSWORD: findhotel
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
